### ISSUE TITLE
Small fix in the steps to install

### ISSUE THREAD

**Issue by branchnetconsulting** [olivere/es#6]
The setup process in the README:
  $ git clone https://github.com/olivere/es
  $ go get
  $ go build
  $ ./es help
is missing a 
  $ cd es-master
between the "git" and the "go get" lines

**Comment by olivere** [comment]
@branchnetconsulting Hi there. Are you using it against ES 1.x or 2.x. This tool is only supported for 1.x.

**Comment by olivere** [comment]
@branchnetconsulting Oops. Sorry, wrong ticket...

**Comment by olivere** [comment]
I fixed the installation steps. But as I said in #5: This tool only works for Elasticsearch 1.x and I currently don't have the time to port it to 2.x.

**Comment by branchnetconsulting** [comment]
Ah, thanks for clarifying.  Yes I am using the latest stable ES so this
project isn't for me.  Thanks for pointing that out.
