### ISSUE TITLE
"go get" never completes

### ISSUE THREAD

**Issue by branchnetconsulting** [olivere/es#7]
When I ran "go get", nothing happened.  After a long wait I cancelled it and ran "go -v get", which gets this far and hangs:

Fetching https://gopkg.in/olivere/elastic.v2/uritemplates?go-get=1
Parsing meta tags from https://gopkg.in/olivere/elastic.v2/uritemplates?go-get=1 (status code 200)
get "gopkg.in/olivere/elastic.v2/uritemplates": found meta tag main.metaImport{Prefix:"gopkg.in/olivere/elastic.v2", VCS:"git", RepoRoot:"https://gopkg.in/olivere/elastic.v2"} at https://gopkg.in/olivere/elastic.v2/uritemplates?go-get=1
get "gopkg.in/olivere/elastic.v2/uritemplates": verifying non-authoritative meta tag
Fetching https://gopkg.in/olivere/elastic.v2?go-get=1
Parsing meta tags from https://gopkg.in/olivere/elastic.v2?go-get=1 (status code 200)
gopkg.in/olivere/elastic.v2 (download)

I've retried repeatedly and still the same problem.

Is this a transient issue or is something broken?

Here is the exact process I used on CentOS 6.7 with go version go1.5.1 linux/amd64:

wget https://github.com/olivere/es/archive/master.zip
unzip master.zip
cd es-master
mkdir /go
GOPATH=/go
export GOPATH
go get
(hang)

I tried something similar on an Ubuntu 14.04 box and "go get" segfaulted.

**Comment by olivere** [comment]
@branchnetconsulting I just did this on OS X and it works fine with Go 1.6 and Git 2.8.1:

```sh
$ go get github.com/olivere/es
$ cd $GOPATH/src/github.com/olivere/es
$ go build
$ ./es help
```

I know that there used to be a problem with old versions of Git not working with go get. So do you have a recent version of git installed?

**Comment by olivere** [comment]
Closing, probably resolved by now.
